spring.application.name=BirdSight

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/birdsight}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:birdsight_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:birdsight_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
