import { MapObservation } from "@/app/types/explore";

export const MAP_OBSERVATIONS: MapObservation[] = [
  {
    id: 1,
    species: "Atlantic Puffin",
    speciesScientific: "Fratercula arctica",
    location: "Skomer Island, Wales",
    user: "alex_birder",
    timeAgo: "2 hours ago",
    badge: "Rare",
    badgeColor: "bg-rose-100 text-rose-700",
    emoji: "🐦",
    latitude: 51.7358,
    longitude: -5.2983,
  },
  {
    id: 2,
    species: "Peregrine Falcon",
    speciesScientific: "Falco peregrinus",
    location: "Central Park, New York",
    user: "sarah_w",
    timeAgo: "4 hours ago",
    badge: "Lifer",
    badgeColor: "bg-emerald-100 text-emerald-700",
    emoji: "🦅",
    latitude: 40.7829,
    longitude: -73.9654,
  },
  {
    id: 3,
    species: "European Bee-eater",
    speciesScientific: "Merops apiaster",
    location: "Algarve, Portugal",
    user: "joao.ferreira",
    timeAgo: "6 hours ago",
    badge: null,
    badgeColor: "",
    emoji: "🐝",
    latitude: 37.0179,
    longitude: -7.9304,
  },
  {
    id: 4,
    species: "Snowy Owl",
    speciesScientific: "Bubo scandiacus",
    location: "Manitoba, Canada",
    user: "tundra_watcher",
    timeAgo: "8 hours ago",
    badge: "Rare",
    badgeColor: "bg-rose-100 text-rose-700",
    emoji: "🦉",
    latitude: 50.4452,
    longitude: -98.9553,
  },
  {
    id: 5,
    species: "Kingfisher",
    speciesScientific: "Alcedo atthis",
    location: "River Thames, London",
    user: "urban_birder",
    timeAgo: "10 hours ago",
    badge: null,
    badgeColor: "",
    emoji: "🐟",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 6,
    species: "Resplendent Quetzal",
    speciesScientific: "Pharomachrus mocinno",
    location: "Monteverde, Costa Rica",
    user: "carlos.r",
    timeAgo: "1 day ago",
    badge: "Featured",
    badgeColor: "bg-violet-100 text-violet-700",
    emoji: "🌿",
    latitude: 10.3025,
    longitude: -84.8245,
  },
  {
    id: 7,
    species: "Japanese Crane",
    speciesScientific: "Grus japonensis",
    location: "Hokkaido, Japan",
    user: "yuki_nature",
    timeAgo: "1 day ago",
    badge: "Rare",
    badgeColor: "bg-rose-100 text-rose-700",
    emoji: "🏔️",
    latitude: 43.0646,
    longitude: 141.3468,
  },
  {
    id: 8,
    species: "Superb Fairywren",
    speciesScientific: "Malurus cyaneus",
    location: "Sydney, Australia",
    user: "aussie_birder",
    timeAgo: "1 day ago",
    badge: null,
    badgeColor: "",
    emoji: "💎",
    latitude: -33.8688,
    longitude: 151.2093,
  },
  {
    id: 9,
    species: "Lilac-breasted Roller",
    speciesScientific: "Coracias caudatus",
    location: "Serengeti, Tanzania",
    user: "safari_watcher",
    timeAgo: "2 days ago",
    badge: "Featured",
    badgeColor: "bg-violet-100 text-violet-700",
    emoji: "🌅",
    latitude: -2.3333,
    longitude: 34.8333,
  },
  {
    id: 10,
    species: "Andean Condor",
    speciesScientific: "Vultur gryphus",
    location: "Colca Canyon, Peru",
    user: "andean_explorer",
    timeAgo: "2 days ago",
    badge: "Rare",
    badgeColor: "bg-rose-100 text-rose-700",
    emoji: "🏔️",
    latitude: -15.6089,
    longitude: -71.1053,
  },
  {
    id: 11,
    species: "Flamingo",
    speciesScientific: "Phoenicopterus roseus",
    location: "Camargue, France",
    user: "med_birder",
    timeAgo: "2 days ago",
    badge: null,
    badgeColor: "",
    emoji: "🦩",
    latitude: 43.5283,
    longitude: 4.5361,
  },
  {
    id: 12,
    species: "Bald Eagle",
    speciesScientific: "Haliaeetus leucocephalus",
    location: "Alaska, USA",
    user: "eagle_eye",
    timeAgo: "3 days ago",
    badge: null,
    badgeColor: "",
    emoji: "🦅",
    latitude: 58.3005,
    longitude: -134.4197,
  },
];
