import { Observation } from "@/app/types/landing";

export const RECENT_OBSERVATIONS: Observation[] = [
  {
    id: 1,
    species: "Atlantic Puffin",
    location: "Skomer Island, Wales",
    user: "alex_birder",
    timeAgo: "2 hours ago",
    badge: "Rare",
    badgeColor: "bg-rose-100 text-rose-700",
    emoji: "🐦",
    gradient: "from-sky-100 to-blue-200",
  },
  {
    id: 2,
    species: "Peregrine Falcon",
    location: "Central Park, New York",
    user: "sarah_w",
    timeAgo: "4 hours ago",
    badge: "Lifer",
    badgeColor: "bg-emerald-100 text-emerald-700",
    emoji: "🦅",
    gradient: "from-stone-100 to-stone-200",
  },
  {
    id: 3,
    species: "European Bee-eater",
    location: "Algarve, Portugal",
    user: "joao.ferreira",
    timeAgo: "6 hours ago",
    badge: null,
    badgeColor: "",
    emoji: "🐝",
    gradient: "from-amber-100 to-yellow-200",
  },
  {
    id: 4,
    species: "Snowy Owl",
    location: "Manitoba, Canada",
    user: "tundra_watcher",
    timeAgo: "8 hours ago",
    badge: "Rare",
    badgeColor: "bg-rose-100 text-rose-700",
    emoji: "🦉",
    gradient: "from-slate-100 to-blue-100",
  },
  {
    id: 5,
    species: "Kingfisher",
    location: "River Thames, London",
    user: "urban_birder",
    timeAgo: "10 hours ago",
    badge: null,
    badgeColor: "",
    emoji: "🐟",
    gradient: "from-teal-100 to-cyan-200",
  },
  {
    id: 6,
    species: "Resplendent Quetzal",
    location: "Monteverde, Costa Rica",
    user: "carlos.r",
    timeAgo: "1 day ago",
    badge: "Featured",
    badgeColor: "bg-violet-100 text-violet-700",
    emoji: "🌿",
    gradient: "from-emerald-100 to-green-200",
  },
];

